### PR TITLE
Publish all artifacts based on the supported build targets

### PR DESCRIPTION
**Pull request by eyedol**
Attempt to fix the issue noted here: https://github.com/dropbox/differ/pull/16#issuecomment-2119081492

### CODE REVIEW

**Comment by takahirom** [comment]
@rharter Sorry for the sudden request. Could you take a moment to merge and release this? We would like to take advantage of KMP.

**Comment by takahirom** [comment]
I understand you don't have time. Just to let you know, I'm considering forking and publishing this repository due to this issue.

**Comment by rharter** [comment]
Sorry, this slipped my radar. I'll take a look on Monday about getting it
merged.

**Review by rharter — APPROVED** [review]

**Comment by takahirom** [comment]
@rharter 
Thank you for merging and attempting to publish. I think we need to create a new token and register it with GitHub Actions.
https://github.com/vanniktech/gradle-maven-publish-plugin/issues/805#issuecomment-2296391217

image

**Comment by rharter** [comment]
Yeah, that's right. Thanks. We just fixed this in another repo today, and I've messaged the admins at work who have access to the sonatype tokens about this one, but it's after hours now, so I expect they'll get to it in the morning. Hopefully we'll have it published soon.

**Pull request merged**
